[ 
  { id: 0,
    category: 'phone',
    name: 'productnamMoto X (4th Generation) - with hands-free Amazon Alexa – 32 GB - Unlocked – Super Black - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71qpbk55hmL._SX522_.jpg',
    price: '$609.00',
    weight: '7 oz' },
  { id: 1,
    category: 'phone',
    name: 'Nokia 6 - 32 GB - Unlocked (AT&T/T-Mobile) - Black',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/51vc-PvR-xL._SX522_.jpg',
    price: '$18.00',
    weight: '5 oz' },
  { id: 2,
    category: 'phone',
    name: 'LG Q6 - 32 GB - Unlocked (AT&T/T-Mobile) - Platinum - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61tdL--e76L._SY679_.jpg',
    price: '$385.00',
    weight: '7 oz' },
  { id: 3,
    category: 'phone',
    name: 'Nokia 2 - 8GB - Unlocked Phone (AT&T/T-Mobile) - 5" Screen - Black (U.S. Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/518zmuwdHzL._SX522_.jpg',
    price: '$640.00',
    weight: '9 oz' },
  { id: 4,
    category: 'phone',
    name: 'Nokia 6 TA-1000 64GB Black, Dual Sim, 5.5", GSM Unlocked International Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/512zZS7f4SL._SX522_.jpg',
    price: '$455.00',
    weight: '7 oz' },
  { id: 5,
    category: 'phone',
    name: 'LG X charge - 16 GB – Unlocked (AT&T/Sprint/T-Mobile) - Titanium - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61KvOuzd4gL._SX522_.jpg',
    price: '$224.00',
    weight: '1 oz' },
  { id: 6,
    category: 'phone',
    name: 'Moto G PLUS (5th Generation) - 32 GB - Unlocked - Lunar Gray - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/715gpXz0dYL._SY679_.jpg',
    price: '$129.00',
    weight: '1 oz' },
  { id: 7,
    category: 'phone',
    name: 'Nokia 6 TA-1000 64GB Silver, Dual Sim, 5.5", GSM Unlocked International Model, No Warranty ',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61XQc%2BFYeBL._SL1000_.jpg',
    price: '$66.00',
    weight: '9 oz' },
  { id: 8,
    category: 'phone',
    name: 'Moto G PLUS (5th Generation) - 64 GB - Unlocked - Lunar Gray - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/715gpXz0dYL._SY679_.jpg',
    price: '$90.00',
    weight: '12 oz' },
  { id: 9,
    category: 'phone',
    name: 'LG G6 - 32 GB - Unlocked (AT&T/T-Mobile/Verizon) - Platinum - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71eqmzFN7CL._SY679_.jpg',
    price: '$585.00',
    weight: '2 oz' },
  { id: 10,
    category: 'phone',
    name: 'Nokia 8 TA-1052 64GB Polished Copper, Dual Sim, 5.4", 4GB RAM, GSM Unlocked International Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/41xTHkyKgnL.jpg',
    price: '$399.00',
    weight: '9 oz' },
  { id: 11,
    category: 'phone',
    name: 'Moto E (4th Generation) - 16 GB - Unlocked (AT&T/Sprint/T-Mobile/Verizon) - Black - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/616l8dGb3lL._SX522_.jpg',
    price: '$553.00',
    weight: '8 oz' },
  { id: 12,
    category: 'phone',
    name: 'LG Electronics LGUS601.AUSASV X Charge Unlocked Phone - 16GB - 5.5" - Silver (U.S. Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81KoFhuT%2BzL._SY679_.jpg',
    price: '$683.00',
    weight: '13 oz' },
  { id: 13,
    category: 'phone',
    name: 'Nokia 6 Case, Yiakeng Nature TPU Soft Cover Crystal Case Clear Skin Soft Case Slim Case for Nokia6 5.5" (Clear)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61x54F0s4bL._SX522_.jpg',
    price: '$402.00',
    weight: '14 oz' },
  { id: 14,
    category: 'phone',
    name: 'Nokia 6 Case, Dretal [Shock Resistant] Flexible Soft TPU Brushed Anti-fingerprint Full-body Protective Case Cover For Nokia 6 (5.5") (Red)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61A5wrZcNgL._SX522_.jpg',
    price: '$508.00',
    weight: '6 oz' },
  { id: 15,
    category: 'phone',
    name: 'Nokia 5 TA-1053 16GB, Dual Sim, 5.2", Factory Unlocked International Model, No Warranty - GSM ONLY, NO CDMA (Blue)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61A0jmawunL._SX522_.jpg',
    price: '$281.00',
    weight: '6 oz' },
  { id: 16,
    category: 'phone',
    name: 'Essential Phone 128 GB Unlocked with Full Display, Dual Camera – Black Moon',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81OvOMun5zL._SX522_.jpg',
    price: '$644.00',
    weight: '1 oz' },
  { id: 17,
    category: 'phone',
    name: 'Xiaomi Redmi Note 4 32GB Black, 5.5", Dual Sim, 13MP, GSM Unlocked Global Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71Fk5kYeoiL._SY679_.jpg',
    price: '$465.00',
    weight: '2 oz' },
  { id: 18,
    category: 'phone',
    name: 'Sony Xperia L1 - Unlocked Smartphone - 16GB - Black (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71%2B0yjSNyVL._SY679_.jpg',
    price: '$759.00',
    weight: '2 oz' },
  { id: 19,
    category: 'phone',
    name: 'Unlocked Cell Phones, DOOGEE X20 Smartphone Unlocked Android 7.0 - 5.0" HD IPS Display - 1GB RAM + 16GB ROM - 5MP Dual Cameras - 3G Unlocked Phones - Black',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71oS8Xo8jlL._SX522_.jpg',
    price: '$233.00',
    weight: '11 oz' },
  { id: 20,
    category: 'phone',
    name: 'Sony Xperia L1 16GB 5.5-inch Smartphone, Unlocked Pink (1308-0910) w/ VR Accessory Bundle Includes, Virtual Reality Cinema Viewer with Insulated Audio System & 32GB MicroSD High-Speed Memory Card',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61F8WTKx4jL._SL1000_.jpg',
    price: '$569.00',
    weight: '13 oz' },
  { id: 21,
    category: 'phone',
    name: 'Sony Xperia XA1 - Unlocked Smartphone - 32GB - White (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71oTbQBhpiL._SX522_.jpg',
    price: '$527.00',
    weight: '6 oz' },
  { id: 22,
    category: 'phone',
    name: 'Sony Xperia XA unlocked smartphone,16GB Black (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71iaaasXEgL._SY679_.jpg',
    price: '$763.00',
    weight: '6 oz' },
  { id: 23,
    category: 'phone',
    name: 'SONY XPERIA E5 Black (F3313) (UNLOCKED) LTE 5.0" / 16GB-1.5GB RAM / 13MP SMARTPHONE - 1 year US WARRANTY!',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61TCI8BRZqL._SY679_.jpg',
    price: '$433.00',
    weight: '6 oz' },
  { id: 24,
    category: 'phone',
    name: 'Nokia 3 TA-1032 4G LTE Dual sim 16GB Android 7.0 2GB Ram 8MP International Version No Warranty (Silver/White)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61k%2BXS1GLHL._SX522_.jpg',
    price: '$404.00',
    weight: '7 oz' },
  { id: 25,
    name: 'Panasonic RP-HJE120-PPK In-Ear Stereo Earphones, Black',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/31T7cG1RxpL.jpg',
    price: '$289.00',
    weight: '10 oz' },
  { id: 26,
    name: 'Mpow 059 Bluetooth Headphones Over Ear, Hi-Fi Stereo Wireless Headset, Foldable, Soft Memory-Protein Earmuffs, w/ Built-in Mic and Wired Mode for PC/ Cell Phones/ TV',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61y0yb%2B3pqL._SL1280_.jpg',
    price: '$204.00',
    weight: '15 oz' },
  { id: 27,
    name: 'Halcent 2 Pack Premium Wired Earphones Noise Cancelling Earbuds Headphones with Remote & Mic In-Ear Headphones for iPhone, Samsung, iPad, iPod, Nokia, LG, HTC etc (White)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61cFs0XjzFL._SL1500_.jpg',
    price: '$426.00',
    weight: '9 oz' },
  { id: 28,
    name: 'Halcent 2 Pack Stereo Sound Earphones,Noise Cancelling Headphones with Microphone,Stylish Dynamic Rope Wired Earbuds for iPhone, Samsung, iPad, iPod, Nokia, LG, HTC etc(Black & Red)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71dCtpr8REL._SL1500_.jpg',
    price: '$748.00',
    weight: '5 oz' },
  { id: 29,
    name: 'Earbuds, HokoAcc In-Ear Headphones Noise Isolation Headsets Heavy Bass Earphones with Microphone for iPhone Samsung iPad and Most Android Phones',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/51vWsEvnVJL._SL1050_.jpg',
    price: '$378.00',
    weight: '14 oz' },
  { id: 30,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61GIxxfDvKL._SL1280_.jpg',
    price: '$1.00',
    weight: '1 oz' },
  { id: 31,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61VcjWqmBSL._SL1280_.jpg',
    price: '$233.00',
    weight: '1 oz' },
  { id: 32,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61L2yUAOKeL._SL1280_.jpg',
    price: '$753.00',
    weight: '9 oz' },
  { id: 33,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61UtzTmRkmL._SL1280_.jpg',
    price: '$506.00',
    weight: '4 oz' },
  { id: 34,
    name: 'On Ear Headphones, Vogek Lightweight and Foldable Bass Headphones with Volume Control and Microphone-Black',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71es1iBWE-L._SL1500_.jpg',
    price: '$701.00',
    weight: '7 oz' },
  { id: 35,
    name: 'Vogek On Ear Headphones Lightweight and Foldable Bass Headphones with Volume Control and Microphone - Blue',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71HavkRJuOL._SL1500_.jpg',
    price: '$36.00',
    weight: '14 oz' },
  { id: 36,
    name: 'On Ear Headphones, Vogek Lightweight and Foldable On Ear Headphones with 1.5M Tangle-Free Cord and Microphone - Cyan',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71WoLs1CO3L._SL1500_.jpg',
    price: '$797.00',
    weight: '15 oz' },
  { id: 37,
    name: 'Vogek On Ear Headphones Lightweight and Foldable Bass Headphones with Volume Control and Microphone (Gold-White)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71R7jKxQxXL._SL1500_.jpg',
    price: '$775.00',
    weight: '6 oz' },
  { id: 38,
    name: 'On Ear Headphones, Vogek Lightweight and Foldable On Ear Headphones with 1.5M Tangle-Free Cord and Microphone - Red',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71VJaOr3gnL._SL1500_.jpg',
    price: '$710.00',
    weight: '10 oz' },
  { id: 39,
    name: 'Bluetooth Headphones, Otium Best Wireless Sports Earphones w/ Mic IPX7 Waterproof HD Stereo Sweatproof In Ear Earbuds for Gym Running Workout 8 Hour Battery Noise Cancelling Headsets',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61a9fpKy3qL._SL1500_.jpg',
    price: '$353.00',
    weight: '4 oz' },
  { id: 40,
    name: 'Purina Cat Chow Naturals Indoor Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81XKRgX0CbL._SL1500_.jpg',
    price: '$199.00',
    weight: '2 oz' },
  { id: 41,
    name: 'Meow Mix Tender Centers Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71e%2BOBGQk5L._SL1300_.jpg',
    price: '$72.00',
    weight: '16 oz' },
  { id: 42,
    name: '9Lives Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81tMyZtpHRL._SL1300_.jpg',
    price: '$214.00',
    weight: '13 oz' },
  { id: 43,
    name: 'Purina Friskies Surfin\' & Turfin\' Favorites Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81iY6Jf-QHL._SL1500_.jpg',
    price: '$781.00',
    weight: '4 oz' },
  { id: 44,
    name: 'Purina Friskies Savory Shreds Adult Wet Cat Food Variety Pack',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81iY6Jf-QHL._SL1500_.jpg',
    price: '$440.00',
    weight: '5 oz' },
  { id: 45,
    name: 'Purina ONE Tender Selects Blend With Real Chicken Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81xfG2foxVL._SL1500_.jpg',
    price: '$622.00',
    weight: '2 oz' },
  { id: 46,
    name: 'Purina Fancy Feast Medleys Tuscany Collection Gourmet Wet Cat Food Variety Pack- (24) 3 oz. Cans',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81mbzXlXN8L._SL1500_.jpg',
    price: '$637.00',
    weight: '10 oz' },
  { id: 47,
    name: 'Purina Friskies Tasty Treasures Variety Pack Wet Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/91i3WownEhL._SL1500_.jpg',
    price: '$669.00',
    weight: '5 oz' },
  { id: 48,
    name: 'IAMS Proactive Health Specialized Care Adult Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/818NOD6F1XL._SL1500_.jpg',
    price: '$773.00',
    weight: '5 oz' },
  { id: 49,
    name: 'BLUE Wilderness High Protein Grain Free Adult Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/91Ry9TwrYkL._SL1500_.jpg',
    price: '$33.00',
    weight: '4 oz' },
  { id: 50,
    name: 'Explorer',
    price: '$955.00',
    weight: '4 lbs',
    manufacturer: 'AeroVironment',
    dimensions: '14 x 11 x 9 inches',
    color: 'Azure',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-00.jpg?itok=lfMW1KUQ&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 291 },
  { id: 51,
    name: 'Spark',
    price: '$1125.00',
    weight: '5 lbs',
    manufacturer: 'Lockheed Martin',
    dimensions: '4 x 8 x 19 inches',
    color: 'Slate',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-08.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 0,
    reviewNumber: 237 },
  { id: 52,
    name: 'Halo',
    price: '$744.00',
    weight: '4 lbs',
    manufacturer: 'Northrop Grumman',
    dimensions: '8 x 3 x 12 inches',
    color: 'Slate',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 292 },
  { id: 53,
    name: 'Bebop 1',
    price: '$597.00',
    weight: '5 lbs',
    manufacturer: 'Northrop Grumman',
    dimensions: '3 x 14 x 16 inches',
    color: 'White',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 150 },
  { id: 54,
    name: 'Eagle',
    price: '$1136.00',
    weight: '2 lbs',
    manufacturer: 'Boeing',
    dimensions: '14 x 11 x 8 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-00.jpg?itok=lfMW1KUQ&fc=50,50',
    category: 'drone',
    overallReview: 5,
    reviewNumber: 250 },
  { id: 55,
    name: 'Marlin',
    price: '$369.00',
    weight: '1 lbs',
    manufacturer: '3D Robotics',
    dimensions: '19 x 17 x 17 inches',
    color: 'Slate',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 202 },
  { id: 56,
    name: 'Marlin',
    price: '$373.00',
    weight: '4 lbs',
    manufacturer: 'Yuneec',
    dimensions: '16 x 14 x 18 inches',
    color: 'Azure',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 0,
    reviewNumber: 102 },
  { id: 57,
    name: 'Titan',
    price: '$1017.00',
    weight: '3 lbs',
    manufacturer: 'Yuneec',
    dimensions: '4 x 3 x 12 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-08.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 338 },
  { id: 58,
    name: 'Hanyu',
    price: '$551.00',
    weight: '2 lbs',
    manufacturer: 'AeroVironment',
    dimensions: '5 x 3 x 2 inches',
    color: 'Azure',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-07.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 288 },
  { id: 59,
    name: 'Man-Bat',
    price: '$1148.00',
    weight: '6 lbs',
    manufacturer: 'Parrot SA',
    dimensions: '6 x 2 x 9 inches',
    color: 'Black',
    image_url: 'https://cdn.vox-cdn.com/thumbor/vPg3038R00gWj4tzgYQS1lDb5Y8=/0x0:1024x576/920x613/filters:focal(431x207:593x369):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/56508181/Drone_LIlY_00011_1024x576.0.png',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 9 },
  { id: 60,
    name: 'Platinum Fly',
    price: '$692.00',
    weight: '5 lbs',
    manufacturer: 'Boeing',
    dimensions: '18 x 6 x 8 inches',
    color: 'Vermillion',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 358 },
  { id: 61,
    name: 'Henry',
    price: '$750.00',
    weight: '6 lbs',
    manufacturer: 'Lockheed Martin',
    dimensions: '12 x 9 x 18 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-04.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 151 },
  { id: 62,
    name: 'Galileo',
    price: '$1153.00',
    weight: '6 lbs',
    manufacturer: 'Northrop Grumman',
    dimensions: '19 x 16 x 2 inches',
    color: 'Slate',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-03.jpg?itok=ZDWebsXe&fc=50,50',
    category: 'drone',
    overallReview: 0,
    reviewNumber: 115 },
  { id: 63,
    name: 'Marlin',
    price: '$1149.00',
    weight: '6 lbs',
    manufacturer: 'Boeing',
    dimensions: '14 x 18 x 4 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-08.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 120 },
  { id: 64,
    name: 'Platinum Fly',
    price: '$148.00',
    weight: '1 lbs',
    manufacturer: 'Dajiang Innovations',
    dimensions: '19 x 9 x 16 inches',
    color: 'Slate',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-01.jpg?itok=i7bfo9cK&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 124 },
  { id: 65,
    name: 'Explorer',
    price: '$237.00',
    weight: '5 lbs',
    manufacturer: 'Boeing',
    dimensions: '11 x 5 x 17 inches',
    color: 'Vermillion',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-04.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 172 },
  { id: 66,
    name: 'Falcon',
    price: '$792.00',
    weight: '2 lbs',
    manufacturer: 'Yuneec',
    dimensions: '16 x 1 x 10 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 164 },
  { id: 67,
    name: 'Lead Ballon',
    price: '$671.00',
    weight: '2 lbs',
    manufacturer: 'AeroVironment',
    dimensions: '15 x 15 x 17 inches',
    color: 'Crimson',
    image_url: 'https://dev.cdn.wetalkuav.com/wp-content/uploads/2018/02/08010609/mind-control-drones-1024x678.jpg',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 259 },
  { id: 68,
    name: 'Typhoon',
    price: '$971.00',
    weight: '1 lbs',
    manufacturer: '3D Robotics',
    dimensions: '15 x 12 x 6 inches',
    color: 'Azure',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-01.jpg?itok=i7bfo9cK&fc=50,50',
    category: 'drone',
    overallReview: 5,
    reviewNumber: 324 },
  { id: 69,
    name: 'Constitution',
    price: '$347.00',
    weight: '6 lbs',
    manufacturer: 'Northrop Grumman',
    dimensions: '10 x 21 x 17 inches',
    color: 'Azure',
    image_url: 'https://cdn2.harveynorman.com.au/media/catalog/product/cache/21/image/992x558/9df78eab33525d08d6e5fb8d27136e95/3/4/3495037_1.jpg',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 154 },
  { id: 70,
    name: 'Titan',
    price: '$1084.00',
    weight: '1 lbs',
    manufacturer: '3D Robotics',
    dimensions: '15 x 6 x 4 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 259 },
  { id: 71,
    name: 'Bebop 2',
    price: '$224.00',
    weight: '5 lbs',
    manufacturer: '3D Robotics',
    dimensions: '5 x 4 x 7 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-08.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 272 },
  { id: 72,
    name: 'Challenger',
    price: '$821.00',
    weight: '2 lbs',
    manufacturer: 'Boeing',
    dimensions: '21 x 14 x 18 inches',
    color: 'Black',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 337 },
  { id: 73,
    name: 'Henry',
    price: '$3.00',
    weight: '4 lbs',
    manufacturer: 'Dajiang Innovations',
    dimensions: '9 x 12 x 19 inches',
    color: 'Azure',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-07.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 5,
    reviewNumber: 99 },
  { id: 74,
    name: 'Lead Ballon',
    price: '$635.00',
    weight: '6 lbs',
    manufacturer: '3D Robotics',
    dimensions: '11 x 17 x 5 inches',
    color: 'Black',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 0,
    reviewNumber: 16 },
  { id: 75,
    name: 'Sony-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/WnZqdY',
    price: '$778.00',
    weight: '5 oz' },
  { id: 76,
    name: 'Vizio-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/aw6khe',
    price: '$451.00',
    weight: '16 oz' },
  { id: 77,
    name: 'Philips-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/BFRLPi',
    price: '$629.00',
    weight: '1 oz' },
  { id: 78,
    name: 'Samsung-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/t4HW6Q',
    price: '$525.00',
    weight: '4 oz' },
  { id: 79,
    name: 'TCL-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/6wpBKq',
    price: '$462.00',
    weight: '5 oz' },
  { id: 80,
    name: 'LG-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/myL1tv',
    price: '$506.00',
    weight: '11 oz' },
  { id: 81,
    name: 'undefined-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/7NmS2A',
    price: '$466.00',
    weight: '11 oz' },
  { id: 82,
    name: 'Sony-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/CNzaV1',
    price: '$729.00',
    weight: '9 oz' },
  { id: 83,
    name: 'Vizio-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/ypwmt1',
    price: '$396.00',
    weight: '15 oz' },
  { id: 84,
    name: 'Philips-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/RoVfZb',
    price: '$469.00',
    weight: '8 oz' },
  { id: 85,
    name: 'Samsung-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/qJgKz5',
    price: '$143.00',
    weight: '7 oz' },
  { id: 86,
    name: 'TCL-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/u68PL7',
    price: '$403.00',
    weight: '11 oz' },
  { id: 87,
    name: 'LG-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/er6emf',
    price: '$512.00',
    weight: '15 oz' },
  { id: 88,
    name: 'undefined-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/7Rq9BV',
    price: '$537.00',
    weight: '14 oz' },
  { id: 89,
    name: 'Sony-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/ZGqiKk',
    price: '$649.00',
    weight: '7 oz' },
  { id: 90,
    name: 'Vizio-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/qHFMdA',
    price: '$127.00',
    weight: '4 oz' },
  { id: 91,
    name: 'Philips-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/u9Q8DR',
    price: '$367.00',
    weight: '13 oz' },
  { id: 92,
    name: 'Samsung-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/aVSsYn',
    price: '$134.00',
    weight: '16 oz' },
  { id: 93,
    name: 'TCL-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/oj4pSr',
    price: '$635.00',
    weight: '7 oz' },
  { id: 94,
    name: 'LG-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/SSJw9D',
    price: '$188.00',
    weight: '7 oz' },
  { id: 95,
    name: 'undefined-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/88vHa9',
    price: '$631.00',
    weight: '16 oz' },
  { id: 96,
    name: 'Sony-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/JoWhVh',
    price: '$767.00',
    weight: '13 oz' },
  { id: 97,
    name: 'Vizio-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/18VjJX',
    price: '$324.00',
    weight: '9 oz' },
  { id: 98,
    name: 'Philips-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/fVmpkb',
    price: '$231.00',
    weight: '16 oz' },
  { id: 99,
    name: 'Samsung-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/RtURx5',
    price: '$10.00',
    weight: '2 oz' },
]