[
  { id: 50,
    name: 'Mavic Pro',
    price: 525,
    weight: 3,
    manufacturer: 'Ambarella',
    dimensions: '4 x 9 x 6 inches',
    color: 'Vermillion',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 5,
    reviewNumber: 365 },
  { id: 51,
    name: 'Hornet',
    price: 566,
    weight: 6,
    manufacturer: 'Parrot SA',
    dimensions: '7 x 10 x 7 inches',
    color: 'Vermillion',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-02.jpg?itok=ZcNajxlf&fc=50,50',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 256 },
  { id: 52,
    name: 'Titanic',
    price: 999,
    weight: 2,
    manufacturer: 'Dajiang Innovations',
    dimensions: '8 x 7 x 7 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-08.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 81 },
  { id: 53,
    name: 'Spark',
    price: 1018,
    weight: 2,
    manufacturer: 'Ambarella',
    dimensions: '17 x 8 x 6 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-07.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 5,
    reviewNumber: 259 },
  { id: 54,
    name: 'Eagle',
    price: 639,
    weight: 2,
    manufacturer: 'GoPro',
    dimensions: '15 x 8 x 7 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-02.jpg?itok=ZcNajxlf&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 339 },
  { id: 55,
    name: 'Parrot',
    price: 100,
    weight: 2,
    manufacturer: 'Ambarella',
    dimensions: '19 x 12 x 14 inches',
    color: 'Black',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-07.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 394 },
  { id: 56,
    name: 'Tsunami',
    price: 1106,
    weight: 3,
    manufacturer: 'Ambarella',
    dimensions: '3 x 19 x 1 inches',
    color: 'Vermillion',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 293 },
  { id: 57,
    name: 'Constitution',
    price: 1110,
    weight: 4,
    manufacturer: 'Dajiang Innovations',
    dimensions: '5 x 1 x 15 inches',
    color: 'Slate',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 121 },
  { id: 58,
    name: 'Hanyu',
    price: 962,
    weight: 6,
    manufacturer: 'Dajiang Innovations',
    dimensions: '17 x 4 x 6 inches',
    color: 'Vermillion',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 39 },
  { id: 59,
    name: 'Eagle',
    price: 721,
    weight: 2,
    manufacturer: 'Parrot SA',
    dimensions: '16 x 18 x 10 inches',
    color: 'Black',
    image_url: 'https://i0.wp.com/thedronegirl.com/wp-content/uploads/2016/07/MG_1612.jpg?resize=1024%2C683',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 164 },
  { id: 60,
    name: 'Platinum Fly',
    price: 1074,
    weight: 4,
    manufacturer: 'Lockheed Martin',
    dimensions: '4 x 1 x 17 inches',
    color: 'Crimson',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 388 },
  { id: 61,
    name: 'Steadfast',
    price: 1026,
    weight: 2,
    manufacturer: 'Dajiang Innovations',
    dimensions: '18 x 10 x 11 inches',
    color: 'Black',
    image_url: 'https://cdn2.harveynorman.com.au/media/catalog/product/cache/21/image/992x558/9df78eab33525d08d6e5fb8d27136e95/3/4/3495037_1.jpg',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 143 },
  { id: 62,
    name: 'Titan',
    price: 721,
    weight: 3,
    manufacturer: 'GoPro',
    dimensions: '7 x 19 x 20 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-05.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 267 },
  { id: 63,
    name: 'Titan',
    price: 1071,
    weight: 2,
    manufacturer: 'AeroVironment',
    dimensions: '9 x 11 x 20 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-01.jpg?itok=i7bfo9cK&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 304 },
  { id: 64,
    name: 'Warthog',
    price: 408,
    weight: 6,
    manufacturer: 'AeroVironment',
    dimensions: '21 x 12 x 10 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-05.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 211 },
  { id: 65,
    name: 'Warthog',
    price: 287,
    weight: 3,
    manufacturer: 'Northrop Grumman',
    dimensions: '21 x 10 x 21 inches',
    color: 'Vermillion',
    image_url: 'https://dev.cdn.wetalkuav.com/wp-content/uploads/2018/02/08010609/mind-control-drones-1024x678.jpg',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 98 },
  { id: 66,
    name: 'Galileo',
    price: 228,
    weight: 2,
    manufacturer: 'GoPro',
    dimensions: '1 x 7 x 18 inches',
    color: 'Vermillion',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-06.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 127 },
  { id: 67,
    name: 'Hornet',
    price: 844,
    weight: 2,
    manufacturer: 'Northrop Grumman',
    dimensions: '15 x 17 x 10 inches',
    color: 'Slate',
    image_url: 'https://cdn2.harveynorman.com.au/media/catalog/product/cache/21/image/992x558/9df78eab33525d08d6e5fb8d27136e95/3/4/3495037_1.jpg',
    category: 'drone',
    overallReview: 0,
    reviewNumber: 326 },
  { id: 68,
    name: 'Britannia',
    price: 105,
    weight: 2,
    manufacturer: '3D Robotics',
    dimensions: '14 x 1 x 15 inches',
    color: 'Black',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 24 },
  { id: 69,
    name: 'Parrot',
    price: 360,
    weight: 4,
    manufacturer: 'Northrop Grumman',
    dimensions: '1 x 9 x 18 inches',
    color: 'Slate',
    image_url: 'https://www.menkind.co.uk/media/catalog/product/cache/image/1000x/beff4985b56e3afdbeabfc89641a4582/r/a/race_vision_220_fpv_pro_drone_58989_1_.jpg',
    category: 'drone',
    overallReview: 3,
    reviewNumber: 254 },
  { id: 70,
    name: 'Bebop 2',
    price: 351,
    weight: 3,
    manufacturer: 'Parrot SA',
    dimensions: '13 x 12 x 13 inches',
    color: 'Crimson',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-01.jpg?itok=i7bfo9cK&fc=50,50',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 61 },
  { id: 71,
    name: 'Falcon',
    price: 1158,
    weight: 2,
    manufacturer: 'Boeing',
    dimensions: '7 x 2 x 14 inches',
    color: 'Crimson',
    image_url: 'https://truimg.toysrus.com/product/images/sharper-image-rechargeable-dx-2-stunt-drone-2.4-ghz-black--54BCFCEC.zoom.jpg?fit=inside|485:485',
    category: 'drone',
    overallReview: 2,
    reviewNumber: 393 },
  { id: 72,
    name: 'Titanic',
    price: 994,
    weight: 4,
    manufacturer: 'Lockheed Martin',
    dimensions: '20 x 20 x 8 inches',
    color: 'Vermillion',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 4,
    reviewNumber: 370 },
  { id: 73,
    name: 'Titanic',
    price: 607,
    weight: 6,
    manufacturer: 'Dajiang Innovations',
    dimensions: '17 x 4 x 1 inches',
    color: 'White',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-08.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 1,
    reviewNumber: 124 },
  { id: 74,
    name: 'Ivy',
    price: 1080,
    weight: 3,
    manufacturer: 'Lockheed Martin',
    dimensions: '20 x 16 x 6 inches',
    color: 'Azure',
    image_url: 'https://www.popsci.com/sites/popsci.com/files/styles/1000_1x_/public/images/2017/08/drone-09.jpg?itok=dEigMkKk&fc=50,50',
    category: 'drone',
    overallReview: 5,
    reviewNumber: 82 }
]