[
  {
    id: 0,
    category:'phone', 
    name: 'productnamMoto X (4th Generation) - with hands-free Amazon Alexa – 32 GB - Unlocked – Super Black - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71qpbk55hmL._SX522_.jpg',
    },
    {
    id: 1,
    category:'phone', 
    name: 'Nokia 6 - 32 GB - Unlocked (AT&T/T-Mobile) - Black',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/51vc-PvR-xL._SX522_.jpg',
    },
    {
    id: 2,
    category:'phone', 
    name: 'LG Q6 - 32 GB - Unlocked (AT&T/T-Mobile) - Platinum - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61tdL--e76L._SY679_.jpg',
    },
    {
    id: 3,
    category:'phone', 
    name: 'Nokia 2 - 8GB - Unlocked Phone (AT&T/T-Mobile) - 5" Screen - Black (U.S. Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/518zmuwdHzL._SX522_.jpg',
    },
    {
    id: 4,
    category:'phone', 
    name: 'Nokia 6 TA-1000 64GB Black, Dual Sim, 5.5", GSM Unlocked International Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/512zZS7f4SL._SX522_.jpg',
    },
    {
    id: 5,
    category:'phone', 
    name: 'LG X charge - 16 GB – Unlocked (AT&T/Sprint/T-Mobile) - Titanium - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61KvOuzd4gL._SX522_.jpg',
    },
    {
    id: 6,
    category:'phone', 
    name: 'Moto G PLUS (5th Generation) - 32 GB - Unlocked - Lunar Gray - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/715gpXz0dYL._SY679_.jpg',
    },
    {
    id: 7,
    category:'phone', 
    name: 'Nokia 6 TA-1000 64GB Silver, Dual Sim, 5.5", GSM Unlocked International Model, No Warranty ',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61XQc%2BFYeBL._SL1000_.jpg',
    },
    {
    id: 8,
    category:'phone', 
    name: 'Moto G PLUS (5th Generation) - 64 GB - Unlocked - Lunar Gray - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/715gpXz0dYL._SY679_.jpg',
    },
    {
    id: 9,
    category:'phone', 
    name: 'LG G6 - 32 GB - Unlocked (AT&T/T-Mobile/Verizon) - Platinum - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71eqmzFN7CL._SY679_.jpg',
    },
    {
    id: 10,
    category:'phone', 
    name: 'Nokia 8 TA-1052 64GB Polished Copper, Dual Sim, 5.4", 4GB RAM, GSM Unlocked International Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/41xTHkyKgnL.jpg',
    },
    {
    id: 11,
    category:'phone', 
    name: 'Moto E (4th Generation) - 16 GB - Unlocked (AT&T/Sprint/T-Mobile/Verizon) - Black - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/616l8dGb3lL._SX522_.jpg',
    },
    {
    id: 12,
    category:'phone', 
    name: 'LG Electronics LGUS601.AUSASV X Charge Unlocked Phone - 16GB - 5.5" - Silver (U.S. Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81KoFhuT%2BzL._SY679_.jpg',
    },
    {
    id: 13,
    category:'phone', 
    name: 'Nokia 6 Case, Yiakeng Nature TPU Soft Cover Crystal Case Clear Skin Soft Case Slim Case for Nokia6 5.5" (Clear)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61x54F0s4bL._SX522_.jpg',
    },
    {
    id: 14,
    category:'phone', 
    name: 'Nokia 6 Case, Dretal [Shock Resistant] Flexible Soft TPU Brushed Anti-fingerprint Full-body Protective Case Cover For Nokia 6 (5.5") (Red)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61A5wrZcNgL._SX522_.jpg',
    },
    {
    id: 15,
    category:'phone', 
    name: 'Nokia 5 TA-1053 16GB, Dual Sim, 5.2", Factory Unlocked International Model, No Warranty - GSM ONLY, NO CDMA (Blue)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61A0jmawunL._SX522_.jpg',
    },
    {
    id: 16,
    category:'phone', 
    name: 'Essential Phone 128 GB Unlocked with Full Display, Dual Camera – Black Moon',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81OvOMun5zL._SX522_.jpg',
    },
    {
    id: 17,
    category:'phone', 
    name: 'Xiaomi Redmi Note 4 32GB Black, 5.5", Dual Sim, 13MP, GSM Unlocked Global Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71Fk5kYeoiL._SY679_.jpg',
    },
    {
    id: 18,
    category:'phone', 
    name: 'Sony Xperia L1 - Unlocked Smartphone - 16GB - Black (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71%2B0yjSNyVL._SY679_.jpg',
    },
    {
    id: 19,
    category:'phone', 
    name: 'Unlocked Cell Phones, DOOGEE X20 Smartphone Unlocked Android 7.0 - 5.0" HD IPS Display - 1GB RAM + 16GB ROM - 5MP Dual Cameras - 3G Unlocked Phones - Black',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71oS8Xo8jlL._SX522_.jpg',
    },
    {
    id: 20,
    category:'phone', 
    name: 'Sony Xperia L1 16GB 5.5-inch Smartphone, Unlocked Pink (1308-0910) w/ VR Accessory Bundle Includes, Virtual Reality Cinema Viewer with Insulated Audio System & 32GB MicroSD High-Speed Memory Card',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61F8WTKx4jL._SL1000_.jpg',
    },
    {
    id: 21,
    category:'phone', 
    name: 'Sony Xperia XA1 - Unlocked Smartphone - 32GB - White (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71oTbQBhpiL._SX522_.jpg',
    },
    {
    id: 22,
    category:'phone', 
    name: 'Sony Xperia XA unlocked smartphone,16GB Black (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71iaaasXEgL._SY679_.jpg',
    },
    {
    id: 23,
    category:'phone', 
    name: 'SONY XPERIA E5 Black (F3313) (UNLOCKED) LTE 5.0" / 16GB-1.5GB RAM / 13MP SMARTPHONE - 1 year US WARRANTY!',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61TCI8BRZqL._SY679_.jpg',
    },
    {
    id: 24,
    category:'phone', 
    name: 'Nokia 3 TA-1032 4G LTE Dual sim 16GB Android 7.0 2GB Ram 8MP International Version No Warranty (Silver/White)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61k%2BXS1GLHL._SX522_.jpg',
    },
]