[ 
  { id: 0,
    category: 'phone',
    name: 'productnamMoto X (4th Generation) - with hands-free Amazon Alexa – 32 GB - Unlocked – Super Black - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71qpbk55hmL._SX522_.jpg',
    price: '$718.00',
    weight: '6 oz',
    dimensions: '5 x 0.8 x 4 in',
    color: 'Crimson',
    overallReview: 5,
    reviewNumber: 40 },
  { id: 1,
    category: 'phone',
    name: 'Nokia 6 - 32 GB - Unlocked (AT&T/T-Mobile) - Black',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/51vc-PvR-xL._SX522_.jpg',
    price: '$89.00',
    weight: '7 oz',
    dimensions: '6 x 0.9 x 1 in',
    color: 'Black',
    overallReview: 3,
    reviewNumber: 246 },
  { id: 2,
    category: 'phone',
    name: 'LG Q6 - 32 GB - Unlocked (AT&T/T-Mobile) - Platinum - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61tdL--e76L._SY679_.jpg',
    price: '$132.00',
    weight: '5 oz',
    dimensions: '6 x 0.8 x 1 in',
    color: 'White',
    overallReview: 2,
    reviewNumber: 147 },
  { id: 3,
    category: 'phone',
    name: 'Nokia 2 - 8GB - Unlocked Phone (AT&T/T-Mobile) - 5" Screen - Black (U.S. Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/518zmuwdHzL._SX522_.jpg',
    price: '$264.00',
    weight: '3 oz',
    dimensions: '2 x 0.9 x 4 in',
    color: 'Black',
    overallReview: 2,
    reviewNumber: 121 },
  { id: 4,
    category: 'phone',
    name: 'Nokia 6 TA-1000 64GB Black, Dual Sim, 5.5", GSM Unlocked International Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/512zZS7f4SL._SX522_.jpg',
    price: '$455.00',
    weight: '0 oz',
    dimensions: '5 x 0.8 x 0 in',
    color: 'White',
    overallReview: 0,
    reviewNumber: 59 },
  { id: 5,
    category: 'phone',
    name: 'LG X charge - 16 GB – Unlocked (AT&T/Sprint/T-Mobile) - Titanium - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61KvOuzd4gL._SX522_.jpg',
    price: '$240.00',
    weight: '2 oz',
    dimensions: '8 x 0.5 x 1 in',
    color: 'White',
    overallReview: 5,
    reviewNumber: 242 },
  { id: 6,
    category: 'phone',
    name: 'Moto G PLUS (5th Generation) - 32 GB - Unlocked - Lunar Gray - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/715gpXz0dYL._SY679_.jpg',
    price: '$490.00',
    weight: '13 oz',
    dimensions: '8 x 0.5 x 3 in',
    color: 'Vermillion',
    overallReview: 0,
    reviewNumber: 356 },
  { id: 7,
    category: 'phone',
    name: 'Nokia 6 TA-1000 64GB Silver, Dual Sim, 5.5", GSM Unlocked International Model, No Warranty ',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61XQc%2BFYeBL._SL1000_.jpg',
    price: '$98.00',
    weight: '2 oz',
    dimensions: '1 x 0.2 x 3 in',
    color: 'Crimson',
    overallReview: 1,
    reviewNumber: 106 },
  { id: 8,
    category: 'phone',
    name: 'Moto G PLUS (5th Generation) - 64 GB - Unlocked - Lunar Gray - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/715gpXz0dYL._SY679_.jpg',
    price: '$216.00',
    weight: '0 oz',
    dimensions: '1 x 0.9 x 3 in',
    color: 'Black',
    overallReview: 2,
    reviewNumber: 4 },
  { id: 9,
    category: 'phone',
    name: 'LG G6 - 32 GB - Unlocked (AT&T/T-Mobile/Verizon) - Platinum - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71eqmzFN7CL._SY679_.jpg',
    price: '$210.00',
    weight: '6 oz',
    dimensions: '8 x 0.9 x 4 in',
    color: 'Black',
    overallReview: 1,
    reviewNumber: 242 },
  { id: 10,
    category: 'phone',
    name: 'Nokia 8 TA-1052 64GB Polished Copper, Dual Sim, 5.4", 4GB RAM, GSM Unlocked International Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/41xTHkyKgnL.jpg',
    price: '$556.00',
    weight: '2 oz',
    dimensions: '8 x 0.4 x 3 in',
    color: 'Azure',
    overallReview: 4,
    reviewNumber: 313 },
  { id: 11,
    category: 'phone',
    name: 'Moto E (4th Generation) - 16 GB - Unlocked (AT&T/Sprint/T-Mobile/Verizon) - Black - Prime Exclusive',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/616l8dGb3lL._SX522_.jpg',
    price: '$849.00',
    weight: '16 oz',
    dimensions: '4 x 0.1 x 2 in',
    color: 'Black',
    overallReview: 3,
    reviewNumber: 357 },
  { id: 12,
    category: 'phone',
    name: 'LG Electronics LGUS601.AUSASV X Charge Unlocked Phone - 16GB - 5.5" - Silver (U.S. Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81KoFhuT%2BzL._SY679_.jpg',
    price: '$63.00',
    weight: '6 oz',
    dimensions: '2 x 0.7 x 2 in',
    color: 'Azure',
    overallReview: 0,
    reviewNumber: 245 },
  { id: 13,
    category: 'phone',
    name: 'Nokia 6 Case, Yiakeng Nature TPU Soft Cover Crystal Case Clear Skin Soft Case Slim Case for Nokia6 5.5" (Clear)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61x54F0s4bL._SX522_.jpg',
    price: '$499.00',
    weight: '8 oz',
    dimensions: '0 x 0.5 x 1 in',
    color: 'Black',
    overallReview: 0,
    reviewNumber: 168 },
  { id: 14,
    category: 'phone',
    name: 'Nokia 6 Case, Dretal [Shock Resistant] Flexible Soft TPU Brushed Anti-fingerprint Full-body Protective Case Cover For Nokia 6 (5.5") (Red)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61A5wrZcNgL._SX522_.jpg',
    price: '$537.00',
    weight: '2 oz',
    dimensions: '5 x 0 x 2 in',
    color: 'Slate',
    overallReview: 0,
    reviewNumber: 367 },
  { id: 15,
    category: 'phone',
    name: 'Nokia 5 TA-1053 16GB, Dual Sim, 5.2", Factory Unlocked International Model, No Warranty - GSM ONLY, NO CDMA (Blue)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61A0jmawunL._SX522_.jpg',
    price: '$188.00',
    weight: '15 oz',
    dimensions: '0 x 0.3 x 2 in',
    color: 'Slate',
    overallReview: 1,
    reviewNumber: 111 },
  { id: 16,
    category: 'phone',
    name: 'Essential Phone 128 GB Unlocked with Full Display, Dual Camera – Black Moon',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81OvOMun5zL._SX522_.jpg',
    price: '$551.00',
    weight: '9 oz',
    dimensions: '7 x 0.2 x 4 in',
    color: 'Vermillion',
    overallReview: 4,
    reviewNumber: 276 },
  { id: 17,
    category: 'phone',
    name: 'Xiaomi Redmi Note 4 32GB Black, 5.5", Dual Sim, 13MP, GSM Unlocked Global Model, No Warranty',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71Fk5kYeoiL._SY679_.jpg',
    price: '$296.00',
    weight: '14 oz',
    dimensions: '1 x 0.7 x 3 in',
    color: 'Black',
    overallReview: 4,
    reviewNumber: 382 },
  { id: 18,
    category: 'phone',
    name: 'Sony Xperia L1 - Unlocked Smartphone - 16GB - Black (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71%2B0yjSNyVL._SY679_.jpg',
    price: '$34.00',
    weight: '4 oz',
    dimensions: '2 x 0 x 1 in',
    color: 'Black',
    overallReview: 3,
    reviewNumber: 313 },
  { id: 19,
    category: 'phone',
    name: 'Unlocked Cell Phones, DOOGEE X20 Smartphone Unlocked Android 7.0 - 5.0" HD IPS Display - 1GB RAM + 16GB ROM - 5MP Dual Cameras - 3G Unlocked Phones - Black',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71oS8Xo8jlL._SX522_.jpg',
    price: '$345.00',
    weight: '14 oz',
    dimensions: '5 x 0.5 x 2 in',
    color: 'Vermillion',
    overallReview: 3,
    reviewNumber: 370 },
  { id: 20,
    category: 'phone',
    name: 'Sony Xperia L1 16GB 5.5-inch Smartphone, Unlocked Pink (1308-0910) w/ VR Accessory Bundle Includes, Virtual Reality Cinema Viewer with Insulated Audio System & 32GB MicroSD High-Speed Memory Card',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61F8WTKx4jL._SL1000_.jpg',
    price: '$450.00',
    weight: '6 oz',
    dimensions: '4 x 0.3 x 1 in',
    color: 'Crimson',
    overallReview: 3,
    reviewNumber: 321 },
  { id: 21,
    category: 'phone',
    name: 'Sony Xperia XA1 - Unlocked Smartphone - 32GB - White (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71oTbQBhpiL._SX522_.jpg',
    price: '$230.00',
    weight: '9 oz',
    dimensions: '2 x 0.5 x 1 in',
    color: 'Black',
    overallReview: 2,
    reviewNumber: 260 },
  { id: 22,
    category: 'phone',
    name: 'Sony Xperia XA unlocked smartphone,16GB Black (US Warranty)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71iaaasXEgL._SY679_.jpg',
    price: '$104.00',
    weight: '12 oz',
    dimensions: '7 x 0.6 x 3 in',
    color: 'White',
    overallReview: 0,
    reviewNumber: 277 },
  { id: 23,
    category: 'phone',
    name: 'SONY XPERIA E5 Black (F3313) (UNLOCKED) LTE 5.0" / 16GB-1.5GB RAM / 13MP SMARTPHONE - 1 year US WARRANTY!',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61TCI8BRZqL._SY679_.jpg',
    price: '$96.00',
    weight: '4 oz',
    dimensions: '5 x 0.7 x 1 in',
    color: 'White',
    overallReview: 0,
    reviewNumber: 17 },
  { id: 24,
    category: 'phone',
    name: 'Nokia 3 TA-1032 4G LTE Dual sim 16GB Android 7.0 2GB Ram 8MP International Version No Warranty (Silver/White)',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61k%2BXS1GLHL._SX522_.jpg',
    price: '$224.00',
    weight: '11 oz',
    dimensions: '6 x 0.1 x 0 in',
    color: 'White',
    overallReview: 1,
    reviewNumber: 17 },
  { id: 25,
    name: 'Panasonic RP-HJE120-PPK In-Ear Stereo Earphones, Black',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/31T7cG1RxpL.jpg',
    price: '$518.00',
    weight: '9 oz',
    dimensions: '0 x 0.7 x 4 in',
    color: 'Vermillion',
    overallReview: 5,
    reviewNumber: 24 },
  { id: 26,
    name: 'Mpow 059 Bluetooth Headphones Over Ear, Hi-Fi Stereo Wireless Headset, Foldable, Soft Memory-Protein Earmuffs, w/ Built-in Mic and Wired Mode for PC/ Cell Phones/ TV',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61y0yb%2B3pqL._SL1280_.jpg',
    price: '$468.00',
    weight: '4 oz',
    dimensions: '4 x 0.4 x 3 in',
    color: 'Crimson',
    overallReview: 1,
    reviewNumber: 38 },
  { id: 27,
    name: 'Halcent 2 Pack Premium Wired Earphones Noise Cancelling Earbuds Headphones with Remote & Mic In-Ear Headphones for iPhone, Samsung, iPad, iPod, Nokia, LG, HTC etc (White)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61cFs0XjzFL._SL1500_.jpg',
    price: '$623.00',
    weight: '8 oz',
    dimensions: '9 x 0.8 x 2 in',
    color: 'Crimson',
    overallReview: 3,
    reviewNumber: 75 },
  { id: 28,
    name: 'Halcent 2 Pack Stereo Sound Earphones,Noise Cancelling Headphones with Microphone,Stylish Dynamic Rope Wired Earbuds for iPhone, Samsung, iPad, iPod, Nokia, LG, HTC etc(Black & Red)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71dCtpr8REL._SL1500_.jpg',
    price: '$868.00',
    weight: '16 oz',
    dimensions: '1 x 0.4 x 4 in',
    color: 'Vermillion',
    overallReview: 2,
    reviewNumber: 61 },
  { id: 29,
    name: 'Earbuds, HokoAcc In-Ear Headphones Noise Isolation Headsets Heavy Bass Earphones with Microphone for iPhone Samsung iPad and Most Android Phones',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/51vWsEvnVJL._SL1050_.jpg',
    price: '$525.00',
    weight: '15 oz',
    dimensions: '3 x 0 x 4 in',
    color: 'White',
    overallReview: 0,
    reviewNumber: 47 },
  { id: 30,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61GIxxfDvKL._SL1280_.jpg',
    price: '$249.00',
    weight: '5 oz',
    dimensions: '1 x 0.1 x 4 in',
    color: 'Azure',
    overallReview: 3,
    reviewNumber: 92 },
  { id: 31,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61VcjWqmBSL._SL1280_.jpg',
    price: '$982.00',
    weight: '16 oz',
    dimensions: '4 x 0.5 x 2 in',
    color: 'Vermillion',
    overallReview: 2,
    reviewNumber: 8 },
  { id: 32,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61L2yUAOKeL._SL1280_.jpg',
    price: '$160.00',
    weight: '12 oz',
    dimensions: '2 x 0.8 x 4 in',
    color: 'Black',
    overallReview: 2,
    reviewNumber: 109 },
  { id: 33,
    name: 'Mpow Flame Bluetooth Headphones Waterproof IPX7, Wireless Earbuds Sport, Richer Bass HiFi Stereo In-Ear Earphones w/ Mic, Case, 7-9 Hrs Playback Noise Cancelling Headsets (Comfy & Fast Pairing)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61UtzTmRkmL._SL1280_.jpg',
    price: '$179.00',
    weight: '14 oz',
    dimensions: '4 x 0.7 x 1 in',
    color: 'White',
    overallReview: 1,
    reviewNumber: 296 },
  { id: 34,
    name: 'On Ear Headphones, Vogek Lightweight and Foldable Bass Headphones with Volume Control and Microphone-Black',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71es1iBWE-L._SL1500_.jpg',
    price: '$529.00',
    weight: '14 oz',
    dimensions: '2 x 0 x 4 in',
    color: 'White',
    overallReview: 2,
    reviewNumber: 206 },
  { id: 35,
    name: 'Vogek On Ear Headphones Lightweight and Foldable Bass Headphones with Volume Control and Microphone - Blue',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71HavkRJuOL._SL1500_.jpg',
    price: '$34.00',
    weight: '12 oz',
    dimensions: '4 x 0.9 x 4 in',
    color: 'Vermillion',
    overallReview: 0,
    reviewNumber: 337 },
  { id: 36,
    name: 'On Ear Headphones, Vogek Lightweight and Foldable On Ear Headphones with 1.5M Tangle-Free Cord and Microphone - Cyan',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71WoLs1CO3L._SL1500_.jpg',
    price: '$224.00',
    weight: '15 oz',
    dimensions: '0 x 0 x 4 in',
    color: 'White',
    overallReview: 2,
    reviewNumber: 210 },
  { id: 37,
    name: 'Vogek On Ear Headphones Lightweight and Foldable Bass Headphones with Volume Control and Microphone (Gold-White)',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71R7jKxQxXL._SL1500_.jpg',
    price: '$326.00',
    weight: '12 oz',
    dimensions: '0 x 0.7 x 2 in',
    color: 'Crimson',
    overallReview: 5,
    reviewNumber: 302 },
  { id: 38,
    name: 'On Ear Headphones, Vogek Lightweight and Foldable On Ear Headphones with 1.5M Tangle-Free Cord and Microphone - Red',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71VJaOr3gnL._SL1500_.jpg',
    price: '$864.00',
    weight: '7 oz',
    dimensions: '0 x 0.2 x 2 in',
    color: 'Slate',
    overallReview: 3,
    reviewNumber: 68 },
  { id: 39,
    name: 'Bluetooth Headphones, Otium Best Wireless Sports Earphones w/ Mic IPX7 Waterproof HD Stereo Sweatproof In Ear Earbuds for Gym Running Workout 8 Hour Battery Noise Cancelling Headsets',
    category: 'headphones',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/61a9fpKy3qL._SL1500_.jpg',
    price: '$768.00',
    weight: '11 oz',
    dimensions: '9 x 0.1 x 1 in',
    color: 'Vermillion',
    overallReview: 0,
    reviewNumber: 154 },
  { id: 40,
    name: 'Purina Cat Chow Naturals Indoor Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81XKRgX0CbL._SL1500_.jpg',
    price: '$351.00',
    weight: '15 oz',
    dimensions: '4 x 0.6 x 0 in',
    color: 'White',
    overallReview: 3,
    reviewNumber: 41 },
  { id: 41,
    name: 'Meow Mix Tender Centers Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/71e%2BOBGQk5L._SL1300_.jpg',
    price: '$4.00',
    weight: '0 oz',
    dimensions: '1 x 0.1 x 0 in',
    color: 'Slate',
    overallReview: 5,
    reviewNumber: 104 },
  { id: 42,
    name: '9Lives Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81tMyZtpHRL._SL1300_.jpg',
    price: '$363.00',
    weight: '11 oz',
    dimensions: '3 x 0.1 x 3 in',
    color: 'White',
    overallReview: 5,
    reviewNumber: 279 },
  { id: 43,
    name: 'Purina Friskies Surfin\' & Turfin\' Favorites Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81iY6Jf-QHL._SL1500_.jpg',
    price: '$163.00',
    weight: '0 oz',
    dimensions: '0 x 0.8 x 1 in',
    color: 'Azure',
    overallReview: 4,
    reviewNumber: 285 },
  { id: 44,
    name: 'Purina Friskies Savory Shreds Adult Wet Cat Food Variety Pack',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81iY6Jf-QHL._SL1500_.jpg',
    price: '$949.00',
    weight: '15 oz',
    dimensions: '9 x 0.9 x 0 in',
    color: 'Slate',
    overallReview: 1,
    reviewNumber: 68 },
  { id: 45,
    name: 'Purina ONE Tender Selects Blend With Real Chicken Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81xfG2foxVL._SL1500_.jpg',
    price: '$188.00',
    weight: '15 oz',
    dimensions: '4 x 0.1 x 3 in',
    color: 'Slate',
    overallReview: 2,
    reviewNumber: 342 },
  { id: 46,
    name: 'Purina Fancy Feast Medleys Tuscany Collection Gourmet Wet Cat Food Variety Pack- (24) 3 oz. Cans',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/81mbzXlXN8L._SL1500_.jpg',
    price: '$999.00',
    weight: '2 oz',
    dimensions: '7 x 0.9 x 3 in',
    color: 'Crimson',
    overallReview: 3,
    reviewNumber: 118 },
  { id: 47,
    name: 'Purina Friskies Tasty Treasures Variety Pack Wet Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/91i3WownEhL._SL1500_.jpg',
    price: '$121.00',
    weight: '4 oz',
    dimensions: '2 x 0.8 x 3 in',
    color: 'Black',
    overallReview: 2,
    reviewNumber: 375 },
  { id: 48,
    name: 'IAMS Proactive Health Specialized Care Adult Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/818NOD6F1XL._SL1500_.jpg',
    price: '$41.00',
    weight: '1 oz',
    dimensions: '1 x 0.9 x 2 in',
    color: 'Black',
    overallReview: 3,
    reviewNumber: 63 },
  { id: 49,
    name: 'BLUE Wilderness High Protein Grain Free Adult Dry Cat Food',
    category: 'cat food',
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/91Ry9TwrYkL._SL1500_.jpg',
    price: '$109.00',
    weight: '1 oz',
    dimensions: '7 x 0.6 x 4 in',
    color: 'Slate',
    overallReview: 0,
    reviewNumber: 192 }
  ]