[
  { id: 75,
    name: 'Sony-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/WnZqdY',
    price: '$54.00',
    weight: '34 lb',
    dimensions: '13 x 2 x 3 in',
    color: 'Crimson',
    overallReview: 5,
    reviewNumber: 338 },
  { id: 76,
    name: 'Vizio-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/aw6khe',
    price: '$1256.00',
    weight: '41 lb',
    dimensions: '49 x 2 x 33 in',
    color: 'Vermillion',
    overallReview: 0,
    reviewNumber: 196 },
  { id: 77,
    name: 'Philips-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/BFRLPi',
    price: '$1248.00',
    weight: '23 lb',
    dimensions: '21 x 5 x 37 in',
    color: 'Black',
    overallReview: 4,
    reviewNumber: 167 },
  { id: 78,
    name: 'Samsung-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/t4HW6Q',
    price: '$821.00',
    weight: '49 lb',
    dimensions: '45 x 5 x 8 in',
    color: 'Black',
    overallReview: 0,
    reviewNumber: 57 },
  { id: 79,
    name: 'TCL-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/6wpBKq',
    price: '$684.00',
    weight: '26 lb',
    dimensions: '36 x 4 x 30 in',
    color: 'Vermillion',
    overallReview: 1,
    reviewNumber: 196 },
  { id: 80,
    name: 'LG-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/myL1tv',
    price: '$1588.00',
    weight: '35 lb',
    dimensions: '45 x 3 x 28 in',
    color: 'Vermillion',
    overallReview: 4,
    reviewNumber: 66 },
  { id: 81,
    name: 'undefined-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/7NmS2A',
    price: '$1262.00',
    weight: '46 lb',
    dimensions: '2 x 0 x 6 in',
    color: 'Slate',
    overallReview: 4,
    reviewNumber: 58 },
  { id: 82,
    name: 'Sony-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/CNzaV1',
    price: '$39.00',
    weight: '37 lb',
    dimensions: '68 x 2 x 24 in',
    color: 'Azure',
    overallReview: 1,
    reviewNumber: 340 },
  { id: 83,
    name: 'Vizio-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/ypwmt1',
    price: '$126.00',
    weight: '29 lb',
    dimensions: '25 x 5 x 36 in',
    color: 'Vermillion',
    overallReview: 0,
    reviewNumber: 387 },
  { id: 84,
    name: 'Philips-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/RoVfZb',
    price: '$1250.00',
    weight: '5 lb',
    dimensions: '47 x 1 x 1 in',
    color: 'Azure',
    overallReview: 5,
    reviewNumber: 163 },
  { id: 85,
    name: 'Samsung-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/qJgKz5',
    price: '$959.00',
    weight: '5 lb',
    dimensions: '4 x 2 x 30 in',
    color: 'Slate',
    overallReview: 4,
    reviewNumber: 277 },
  { id: 86,
    name: 'TCL-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/u68PL7',
    price: '$507.00',
    weight: '3 lb',
    dimensions: '79 x 9 x 31 in',
    color: 'Azure',
    overallReview: 3,
    reviewNumber: 308 },
  { id: 87,
    name: 'LG-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/er6emf',
    price: '$580.00',
    weight: '40 lb',
    dimensions: '29 x 3 x 23 in',
    color: 'Slate',
    overallReview: 1,
    reviewNumber: 41 },
  { id: 88,
    name: 'undefined-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/7Rq9BV',
    price: '$1201.00',
    weight: '48 lb',
    dimensions: '28 x 8 x 18 in',
    color: 'Crimson',
    overallReview: 1,
    reviewNumber: 362 },
  { id: 89,
    name: 'Sony-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/ZGqiKk',
    price: '$366.00',
    weight: '18 lb',
    dimensions: '54 x 5 x 1 in',
    color: 'White',
    overallReview: 3,
    reviewNumber: 144 },
  { id: 90,
    name: 'Vizio-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/qHFMdA',
    price: '$230.00',
    weight: '26 lb',
    dimensions: '24 x 1 x 30 in',
    color: 'Vermillion',
    overallReview: 1,
    reviewNumber: 249 },
  { id: 91,
    name: 'Philips-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/u9Q8DR',
    price: '$942.00',
    weight: '45 lb',
    dimensions: '17 x 1 x 36 in',
    color: 'Black',
    overallReview: 3,
    reviewNumber: 363 },
  { id: 92,
    name: 'Samsung-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/aVSsYn',
    price: '$674.00',
    weight: '1 lb',
    dimensions: '49 x 5 x 30 in',
    color: 'Black',
    overallReview: 4,
    reviewNumber: 274 },
  { id: 93,
    name: 'TCL-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/oj4pSr',
    price: '$649.00',
    weight: '34 lb',
    dimensions: '13 x 3 x 9 in',
    color: 'Crimson',
    overallReview: 1,
    reviewNumber: 94 },
  { id: 94,
    name: 'LG-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/SSJw9D',
    price: '$549.00',
    weight: '15 lb',
    dimensions: '48 x 6 x 29 in',
    color: 'Slate',
    overallReview: 3,
    reviewNumber: 13 },
  { id: 95,
    name: 'undefined-X',
    category: 'TV',
    image_url: 'https://goo.gl/images/88vHa9',
    price: '$306.00',
    weight: '0 lb',
    dimensions: '32 x 2 x 33 in',
    color: 'Azure',
    overallReview: 3,
    reviewNumber: 235 },
  { id: 96,
    name: 'Sony-B',
    category: 'TV',
    image_url: 'https://goo.gl/images/JoWhVh',
    price: '$1895.00',
    weight: '44 lb',
    dimensions: '39 x 3 x 8 in',
    color: 'Black',
    overallReview: 5,
    reviewNumber: 58 },
  { id: 97,
    name: 'Vizio-V',
    category: 'TV',
    image_url: 'https://goo.gl/images/18VjJX',
    price: '$1207.00',
    weight: '14 lb',
    dimensions: '9 x 5 x 35 in',
    color: 'Black',
    overallReview: 0,
    reviewNumber: 264 },
  { id: 98,
    name: 'Philips-M',
    category: 'TV',
    image_url: 'https://goo.gl/images/fVmpkb',
    price: '$1801.00',
    weight: '19 lb',
    dimensions: '30 x 0 x 31 in',
    color: 'Crimson',
    overallReview: 4,
    reviewNumber: 56 },
  { id: 99,
    name: 'Samsung-undefined',
    category: 'TV',
    image_url: 'https://goo.gl/images/RtURx5',
    price: '$1533.00',
    weight: '37 lb',
    dimensions: '48 x 7 x 19 in',
    color: 'White',
    overallReview: 3,
    reviewNumber: 56 }
]